### ISSUE TITLE
Color Coding text

### ISSUE THREAD

**Issue by TejasNair9977** [TejasNair9977/rpgadv#1]
**Is your feature request related to a problem? Please describe.**
The text is the same color in every single scenario, it would be great if the commands, story, and important messages were given a different color so that it could be easier to read.

**Additional context**
![image](https://user-images.githubusercontent.com/85873779/197750265-7ad68b94-07b2-4de2-816d-a8c7dd7d69b3.png)

**Describe the solution you'd like**
This could be fixed using [termcolor](https://pypi.org/project/termcolor/).
![image](https://user-images.githubusercontent.com/85873779/197750940-6fbd4bb2-0c59-418b-938d-57e6512893d4.png)

**Comment by Athi223** [comment]
I'd like to give this a try

**Comment by TejasNair9977** [comment]
Alright, I have assigned you this issue.
