### ISSUE TITLE
Ability to heal in village

### ISSUE THREAD

**Issue by TejasNair9977** [TejasNair9977/rpgadv#3]
**Is your feature request related to a problem? Please describe.**
We can only drink potions and heal in the middle of fights, so if we are left with 1HP after a fight, we pretty much get instakilled if the next opponent is faster than us, which is dumb. 

**Describe the solution you'd like**
The choices work as if else conditions in challenge.py, (which i know is terrible but still,) simply add another condition which pops potions from our inventory and increases our stats.
![image](https://user-images.githubusercontent.com/85873779/197757726-3dc84c94-258c-421d-8141-52ac23b9ed66.png)

**Comment by ZeroMeOut** [comment]
What if there is a time pause mechanic when using potions and heals to avoid this? I could try coding it up, but it would take some time for me to read through the code to understand what is whar

**Comment by TejasNair9977** [comment]
Ah my description wasn't good enough so let me give some more details. In the game, it's turn based combat and there is only one fight between villages, and you can't heal in those villages, so after a fight, you end up in the village. You can buy health potions there but not use them. When you enter a fight from there, your speed stat determines who gets the first turn, and if your health and speed stats are low, you're pretty much already dead. So if there was an ability to use those health potions in the village it would be great, or maybe even the ability to spend coins to rest at an inn or anything that will increase our health.

**Comment by ZeroMeOut** [comment]
Alright, I get it now. I would fork it to my hub and see what I can do to help :)

**Comment by TejasNair9977** [comment]
Great! I assigned you to this issue.

**Comment by ZeroMeOut** [comment]
I finished adding some changes and did a pull request :)
