### ISSUE TITLE
Make it possible to bulk buy items

### ISSUE THREAD

**Issue by TejasNair9977** [TejasNair9977/rpgadv#5]
**Is your feature request related to a problem? Please describe.**
I have about 2500 coins in my inventory, and I want 25 greatsword upgrades, so i have to go into the shop, buy one, exit, 25 times. Make it so that it asks for the quantity every time you want to purchase something.
![image](https://user-images.githubusercontent.com/85873779/197760239-e9ef838f-5435-4255-bd1a-e70bfa0d6c4a.png)

**Describe the solution you'd like**
The only file you have to modify is challenge.py
More specifically, you only have to change the buy function in that file to add this feature.

**Comment by Athi223** [comment]
Hey! I'd like to contribute to this

**Comment by TejasNair9977** [comment]
Alright! I assigned this issue to you.
